dependencies:
  - name: postgresql
    alias: caliberCategoryPostgresService
    version: 8.4.0
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: caliberCategoryPostgresService.enabled