{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "caliber-category-service.serviceAccountName" . }}
  labels:
{{ include "caliber-category-service.labels" . | indent 4 }}
{{- end -}}
